### ISSUE TITLE
[Dashboard Screen] - Button to copy and paste the Color code in the Widget configuration and Json

### ISSUE THREAD

**Issue by georgevbsantiago** [thinger-io/thinger-server#20]
Cannot copy color code with Ctrl+C. Right-clicking doesn't work either. And Ctrl+V doesn't work either.

OS Windows and Chrome:
![image](https://user-images.githubusercontent.com/22058152/216774184-dbffc0b7-18c3-435d-81cf-dc4e03dec946.png)

Add buttons to copy JSON from the Panel and color code the widgets.

![image](https://user-images.githubusercontent.com/22058152/216774120-837193a9-e028-4a39-8bf8-6245799c2487.png)

**Comment by alvarolb** [comment]
At this moment we are not planning to improve this integration. The color dialog is provided by the browsers, so, we hope browsers improve the picker from time to time.
