### ISSUE TITLE
[Devices Screen] - View devices with Encrypted connection and without Encryption

### ISSUE THREAD

**Issue by georgevbsantiago** [thinger-io/thinger-server#23]
I think it’s important for the platform to signal which devices have an encrypted connection with the Thinger Server.
This information guarantees a better management of devices and allows them to be identified and exchanged in the future by modern devices that allow the connection with encryption.

Example of what I imagined:
![image](https://user-images.githubusercontent.com/22058152/216774724-b478b735-0533-45c5-8aad-dfff6b6105a8.png)

**Comment by alvarolb** [comment]
Included in version 5.1.0
https://community.thinger.io/t/platform-version-5-0-1/4664
