### ISSUE TITLE
[Device Status Screen] - Change State column to inform when the device is ‘Disabled’

### ISSUE THREAD

**Issue by georgevbsantiago** [thinger-io/thinger-server#28]
It would be interesting for the console of the devices to inform which ones are with “Disabled” status and used a different color, eg gray. Or standardize the columns on the bucket list and endpoints screens, changing the column name from “Enabled” to “State”, and insert a new color to represent “Disabled”. Ex: Connected (green); Disconnected (red); Enabled (Blue); Disabled (Gray).

![image](https://user-images.githubusercontent.com/22058152/216777223-283b622e-758b-4495-a4b9-9c4e2d1a3ee7.png)
![image](https://user-images.githubusercontent.com/22058152/216777229-12ccfb4a-f6f9-484c-b790-6cebd0abe141.png)
See the example below:
Wouldn’t it be correct to inform it as Disabled? Can’t users be confused when trying to connect a disabled device because the state says Disconnected?
![image](https://user-images.githubusercontent.com/22058152/216777236-b49208f0-67a9-4129-bcaa-eb951a082566.png)

**Comment by alvarolb** [comment]
Included from version 5.0
https://community.thinger.io/t/platform-version-5-0-1/4664
