### ISSUE TITLE
[Devices Screen] - "Last Connection" caption error

### ISSUE THREAD

**Issue by georgevbsantiago** [thinger-io/thinger-server#39]
When hovering the mouse over the clock icon, all captions appear: "02/25/2023, 14:30".
OS: Windows 10
Browser: Chrome (I have identified the same problem in FireFox)
My Time Zone: -03:00

![image](https://user-images.githubusercontent.com/22058152/221374237-85e39fe3-7742-45e3-916d-b6b0f2a96a6d.png)

![image](https://user-images.githubusercontent.com/22058152/221374189-a73cb256-8f7c-416d-8828-7559c06951e4.png)

**Comment by alvarolb** [comment]
should be fixed on 5.3.0

**Comment by georgevbsantiago** [comment]
Thanks
