### ISSUE TITLE
[Dashboard Screen] - The Widget title overlaps the text of "ts"

### ISSUE THREAD

**Issue by georgevbsantiago** [thinger-io/thinger-server#46]
The title of Widget overlaps the text of "TS".
An alternative (not if the best) would be to displace the text of the "TS" down (see image below):

![image](https://user-images.githubusercontent.com/22058152/222609546-6f6fc774-ac3a-46ae-a702-7228eea60547.png)

**Comment by alvarolb** [comment]
<img width="413" alt="image" src="https://github.com/thinger-io/thinger-server/assets/1141353/262d5f7b-1e9a-4e50-9ef2-13579935252a">

Should be fixed on 5.3.1. At this moment we are adding an ellipsis to the text
