### ISSUE TITLE
Exported data from bucket does not appear when opening screen

### ISSUE THREAD

**Issue by georgevbsantiago** [thinger-io/thinger-server#47]
When opening the screen, the exported data does not appear. Even having exported data (minutes or days ago), they do not appear when opening the screen.
Only when clicking on the "Export" button and when exiting and returning from the screen, is the data visible.

In this print, the previously exported database does not show. The exported data only appears after clicking on the export button... exit the screen and come back. Then, the data that already existed (exported 9 minutes ago) and the recently exported data (11 seconds ago) appear.
![image](https://user-images.githubusercontent.com/22058152/225178393-05cc7417-88be-4201-b480-57aa856211be.png)

![bug_2](https://user-images.githubusercontent.com/22058152/225191768-cd4da5a5-b5eb-4c66-8bb3-e19c77c83092.JPG)

**Comment by alvarolb** [comment]
Fixed on 5.3.0
