### ISSUE TITLE
IOTMP not able to send property stream to more than one property

### ISSUE THREAD

**Issue by bautisflow** [thinger-io/thinger-server#49]
**Describe the bug**
When registering multiple property_streams withing the IOTMP client, all resources get the value on registering but only the first resource registered gets further updates

**To Reproduce**
1. In the Linux IOTMP client register two property_streams
2. Launch and update one property within the platform
3. Update the other property

**Expected behavior**
All resources should receive all the updates to their own values

**Comment by alvarolb** [comment]
fixed on 5.3.1
