### ISSUE TITLE
Allow embedding of products web services with security headers

### ISSUE THREAD

**Issue by bautisflow** [thinger-io/thinger-server#51]
**Is your feature request related to a problem? Please describe.**
For example, I can't embed a website like [Klipper Fluidd](https://docs.fluidd.xyz/) to manage a 3D printer within Thinger.io, receiving the following response:
502 Bad Gateway
Referrer Policy: strict-origin-when-cross-origin

**Describe the solution you'd like**
The website should be visible.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by alvarolb** [comment]
Fixed on 5.3.0
