### ISSUE TITLE
Can't create buckets associated to a device resource when device id contains dashes (-)

### ISSUE THREAD

**Issue by bautisflow** [thinger-io/thinger-server#56]
**Describe the bug**
When creating a bucket and configuring the data source to a device resource, if the device id contains dashes (-) a 400 bad request response is given as the schema fails to validate.

**Expected behavior**
Bucket should be created

**Additional context**
https://community.thinger.io/t/cant-create-buckets/4817/3

**Comment by KroegerP** [comment]
This bug is also present for Alarm creation - I received a 400 error while attempting to create alarms and spent 30 minutes trying to debug it until I found this issue.

**Comment by alvarolb** [comment]
Fixed on the upcoming 5.4 version.
