### ISSUE TITLE
[User Management] - Error when trying to change the Project Member's Default Project

### ISSUE THREAD

**Issue by georgevbsantiago** [thinger-io/thinger-server#62]
**1) The Developer user (Ex: "Ted") creates a Project Member (Ex: "Alan") on the Project screen, but is unable to edit the Project Member (Ex: "Alan") profile, like the default project for viewing initial.**
![image](https://github.com/thinger-io/thinger-server/assets/22058152/5d4c47a9-c94f-488b-9d5e-2fbf399463cb)

![image](https://github.com/thinger-io/thinger-server/assets/22058152/7cd0e76a-3c25-45d0-ad77-299f4a45a87e)

**2) The Admin user is unable to edit the Project Member data (Ex: "Alan") created by the Developer (Ex: "Ted").**
![image](https://github.com/thinger-io/thinger-server/assets/22058152/61626d18-c566-4f99-a885-9a4a87a1a13b)

**Comment by alvarolb** [comment]
should be fixed on upcoming version

**Comment by georgevbsantiago** [comment]
Thank you very much, @alvarolb  !

Thinger is always very responsive in serving the community.

**Comment by georgevbsantiago** [comment]
@alvarolb 

This committee caused a BUG in version 5.3.6.
Now the "Developer" user does not create "Project Member" users. And the "Admin" user cannot link the "Project Member" users to the projects created by the "Developer" user.

This is very serious! We need it fixed urgently! We are entering into important contracts right now.
Everything worked fine in version 5.3.3!

See: https://community.thinger.io/t/help-developer-user-does-not-create-project-member-user-in-version-5-3-6/4939/2
