### ISSUE TITLE
[Dashboard Screen] - Flag the widget with “thumb down” when the bucket stops receiving data for a certain period of time 

### ISSUE THREAD

**Issue by georgevbsantiago** [thinger-io/thinger-server#8]
The “thumb down” (or “dislike”) flag (currently adopted by Thinger) is very important to identify if the panel information (in the widgets) is up to date. This prevents the user from making a decision based on data that is out of date due to some problem.

The “problem” is that the “thumb down” flag is currently only available when the widget is configured with the font “From Device Resource”.

The suggestion would be to allow the widget to set the “thumb down” flag with the font “From Data Bucket”.
On the configuration screen (print below), there should be a setting to define the “thumb down” signaling. Ex: If new information is not written to the bucket after 30 minutes, signal “thumb down”.

This is a VERY important indicator for users (especially Project Users…) who are viewing the dashboard and reading and interpreting the data. By viewing the “thumb down” Project Users will know something is wrong and will interpret the data correctly.
As a Developer user, you can quickly identify if there is something wrong with: 1) Data sent from the Device to the Bucket; 2) If there is a problem in NodeRed, if it is used to save data in Bucket; 3) If the browser has not updated the data (this happens frequently when waking Windows from sleep/hibernate mode); 4) If there is any problem with the user’s internet connection.

![image](https://user-images.githubusercontent.com/22058152/216678448-a0bdcf05-58c7-4baf-9dc2-d0a2626a4206.png)
![image](https://user-images.githubusercontent.com/22058152/216678508-0dff2847-a36f-497b-81e6-a8e9a631ad91.png)

**Comment by georgevbsantiago** [comment]
An example of how the user can be misled when interpreting dashboard information.
LED widgets have as "Data Source" "From Data Bucket".
Devices send data every 10 minutes to Bucket.
It turns out that 2 devices were offline for more than 11 hours and stopped sending data to the bucket. Even so, the widget informs the last value sent more than 11 hours ago.
It would be important to have a rule in the widget's configuration to report something wrong, such as "thumbs down" and the LED turning gray, in case the bucket does not receive data for more than 30 minutes, for example.

The lack of this functionality impairs the interpretation of the data.
A simple implementation that could avoid big problems for users (our customers).

![image](https://user-images.githubusercontent.com/22058152/233788047-04aa18f6-915d-47da-99f2-3a0b96f49cf1.png)

**Comment by alvarolb** [comment]
We are adding a new parameter on the Widget Settings, called "Show Offline", where you can establish a timespan, independently if the data comes from a bucket, device, property, etc.

![image](https://github.com/thinger-io/thinger-server/assets/1141353/0bdee74f-8881-4dbc-878a-6c47710b9e73)

Then, if the data is older than this timespan, the widget displays a disconnected icon, and its background turns red to provide noticeable clues that there is some problem with the data.

![image](https://github.com/thinger-io/thinger-server/assets/1141353/c93f63d1-73db-4c45-81c2-e6f69cf988e8)

What do you think?  I am still considering the widget background or other ways to inform the user.

**Comment by georgevbsantiago** [comment]
SENSATIONAL!!!!!!!
This functionality is VERY IMPORTANT!!!!
Thinger will give you a very good user experience!!!
Some opinions:
- I liked the icon to inform "offiline". Very important!
- Regarding the red background, I think the user may want to configure another color. I myself use red to indicate alarm. So, it's better to give the option to the user to assign the color he thinks is best.

**Comment by georgevbsantiago** [comment]
**Other icons that report offline:**
![image](https://github.com/thinger-io/thinger-server/assets/22058152/3cec60ec-6c53-481d-9180-c315e29dc7fd)
![image](https://github.com/thinger-io/thinger-server/assets/22058152/d49bd38b-8579-46f0-964e-214aac0194f4)
![image](https://github.com/thinger-io/thinger-server/assets/22058152/15e1eb83-bddb-43e1-be26-71712011231d)

**Comment by georgevbsantiago** [comment]
A suggestion:
- Only the clock would turn red
![image](https://github.com/thinger-io/thinger-server/assets/22058152/56c06123-2b34-4f47-a966-cecf81f5fe3b)
- And the "offline" icon at the bottom.
![image](https://github.com/thinger-io/thinger-server/assets/22058152/94bce414-7444-4436-aa80-d8ab690c1b63)

This would be an international "offline" icon

**Comment by alvarolb** [comment]
I think we will start with this approach:

- No red background, as it can be annoying if a dashboard is full of disconnected widgets
- Keep the thumb down icon at this moment
- The latest update blinks in red to notify the problem

![alarm](https://github.com/thinger-io/thinger-server/assets/1141353/3f38db6f-74db-45fd-b8a2-b7190b4d76eb)

**Comment by georgevbsantiago** [comment]
Hello @alvarolb 
Should we close this issue?
The implemented solution was very good!

**Comment by alvarolb** [comment]
Yes! We can close it... did you test the feature? Does it work well for you?

**Comment by georgevbsantiago** [comment]
So far, everything working fine.

**Comment by georgevbsantiago** [comment]
> We are adding a new parameter on the Widget Settings, called "Show Offline", where you can establish a timespan, independently if the data comes from a bucket, device, property, etc.
> 
> ![image](https://private-user-images.githubusercontent.com/1141353/248903350-0bdee74f-8881-4dbc-878a-6c47710b9e73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5Mzg3ODgsIm5iZiI6MTcxODkzODQ4OCwicGF0aCI6Ii8xMTQxMzUzLzI0ODkwMzM1MC0wYmRlZTc0Zi04ODgxLTRkYmMtODc4YS02YzQ3NzEwYjllNzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjFUMDI1NDQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzVmMTVkZDU5OWI5ODM5ODVjNDI3MDRlMjRiODUyZjFkNjU5Y2E4ZTRlMGUxNzRjOTk5M2U0NTU3ZDVhOGJhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SG3KHOA8sFiXYm6X89JbkRY_CfPd0lLy6AbxaHYFdvs)
> 
> Then, if the data is older than this timespan, the widget displays a disconnected icon, and its background turns red to provide noticeable clues that there is some problem with the data.
> 
> ![image](https://private-user-images.githubusercontent.com/1141353/248903703-c93f63d1-73db-4c45-81c2-e6f69cf988e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5Mzg3ODgsIm5iZiI6MTcxODkzODQ4OCwicGF0aCI6Ii8xMTQxMzUzLzI0ODkwMzcwMy1jOTNmNjNkMS03M2RiLTRjNDUtODFjMi1lNmY2OWNmOTg4ZTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjFUMDI1NDQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGI0NzQwMDVlZGVkYTBiZDNlZjRiMjI5YmE5MGQyZjU5Y2NmY2JmZmIzOWU2Y2Y2N2FiM2I0ZTA3NjY1NGQ5YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ykxuXf-XRSgzNt7gy6U1lWWmpGmjrfLZJFWSuvUtEPA)
> 
> What do you think? I am still considering the widget background or other ways to inform the user.

We will evolve this idea into a watermark that prevents the user from misreading and misinterpreting the information that is still visible in the widget (although it is out of date).

New implementation suggestion:
https://github.com/thinger-io/thinger-server/issues/101
