### ISSUE TITLE
Add bucket tags in product buckets

### ISSUE THREAD

**Issue by bautisflow** [thinger-io/thinger-server#81]
**Is your feature request related to a problem? Please describe.**
When declaring buckets in products, the possibility to create custom tags should tags, expanding the ones already created by default, which are device and group.

**Describe the solution you'd like**
An additional field with device and group tags greyed out and the possibility to add additional tags.

**Describe alternatives you've considered**
The only alternative that comes to mind is to create the bucket manually before any data from a device associated to the product reaches the platform.

**Comment by alvarolb** [comment]
Done! Will be included in next 6.1.0 release.
