### ISSUE TITLE
[Branding] Not able to upload an icon app on the PWA tab

### ISSUE THREAD

**Issue by bautisflow** [thinger-io/thinger-server#84]
**Describe the bug**
In the PWA tab, it is not possible to upload the app icons, just as it is in the Logos tab. As it seems that these icons are server from the server, due to the local path. It is expected to be able to upload these images.

**Comment by alvarolb** [comment]
Fixed on upcoming release. It will also allow configuring 'any' and 'maskable' icons independently.
