### ISSUE TITLE
HTML Widget (Code Snippet) reports error when a URL has '&'

### ISSUE THREAD

**Issue by georgevbsantiago** [thinger-io/thinger-server#86]
When inserting a URL in an `href` tag with '&' in the body of the string, the HTML Widget editor reports an error.
The error is only corrected if the user replaces '&' with `&amp;` Is this a bug or correct behavior?
Isn't '&' already part of HTML5?

https://stackoverflow.com/questions/15776556/whats-the-difference-between-and-amp-in-html5
https://stackoverflow.com/questions/4441594/w3c-markup-validator-ampersand-error

![image](https://github.com/thinger-io/thinger-server/assets/22058152/97115906-f646-4c9b-994e-0c3397f53094)

**Comment by georgevbsantiago** [comment]
Hi @alvarolb 
With the new Monaco editor, I believe this problem has been resolved.
Can we close?

**Comment by alvarolb** [comment]
Yes! if it is working right now on Monaco...

Thanks for reviewing it!
